[env:esp32-s3-super-mini]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
